### ISSUE TITLE
make: *** [install] Error 2

### ISSUE THREAD

**Issue by jeremymeyers** [davea/homebrew-perlmagick#1]
Getting an error when using this. Log shows:

jeremymeyers$ brew install perlmagick
==> Installing perlmagick from davea/perlmagick
==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-7.0.8-29.tar.xz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/41590d506e2b4a7df7325934cb906db067d5cbb387c80fb05643186c8b6439e3?response-content-disposition=attachment%3Bfilename%3D%22ImageMagick-7.0.8-29.tar.xz%22&Policy=e
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/perlmagick/7.0.8-29 --disable-opencl --enable-shared --enable-static --with-freetype=yes --with-modules --with-openjp2 --with-openexr --with-webp
==> make install
Last 15 lines from /Users/jeremymeyers/Library/Logs/Homebrew/perlmagick/02.make:
libtool: link: clang  -o coders/.libs/jp2.so -bundle  coders/.libs/jp2_la-jp2.o   MagickCore/.libs/libMagickCore-7.Q16HDRI.dylib -L/usr/local/Cellar/little-cms2/2.11/lib -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/xz/5.2.5/lib -lomp -llcms2 -lfreetype -lxml2 -llzma -lbz2 -lz -lltdl -L/usr/local/Cellar/openjpeg/2.3.1/lib -lopenjp2 -lm  -fopenmp -g -O2 -mtune=core2 -pthread   -fopenmp -pthread -Wl,-exported_symbols_list,coders/.libs/jp2-symbols.expsym
libtool: link: mv -f "coders/.libs/webp.expT" "coders/.libs/webp.exp"
libtool: link: sed -e 's|^|_|' < coders/.libs/webp.exp > coders/.libs/webp-symbols.expsym
libtool: link: clang  -o coders/.libs/webp.so -bundle  coders/.libs/webp_la-webp.o   MagickCore/.libs/libMagickCore-7.Q16HDRI.dylib -L/usr/local/Cellar/little-cms2/2.11/lib -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/xz/5.2.5/lib -lomp -llcms2 -lfreetype -lxml2 -llzma -lbz2 -lz -lltdl -L/usr/local/Cellar/webp/1.1.0/lib -lwebpmux -lwebp -lm  -fopenmp -g -O2 -mtune=core2 -pthread   -fopenmp -pthread -Wl,-exported_symbols_list,coders/.libs/webp-symbols.expsym
libtool: link: /usr/bin/grep -E -e ".*" "coders/.libs/tiff.exp" > "coders/.libs/tiff.expT"
libtool: link: mv -f "coders/.libs/tiff.expT" "coders/.libs/tiff.exp"
libtool: link: sed -e 's|^|_|' < coders/.libs/tiff.exp > coders/.libs/tiff-symbols.expsym
libtool: link: clang  -o coders/.libs/tiff.so -bundle  coders/.libs/tiff_la-tiff.o coders/.libs/tiff_la-psd.o   MagickCore/.libs/libMagickCore-7.Q16HDRI.dylib -L/usr/local/Cellar/little-cms2/2.11/lib -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/xz/5.2.5/lib -lomp -llcms2 -lfreetype -lxml2 -lbz2 -lltdl -ltiff -ljpeg -llzma -lz -L/usr/local/Cellar/webp/1.1.0/lib -lwebpmux -lwebp -lm  -fopenmp -g -O2 -mtune=core2 -pthread   -fopenmp -pthread -Wl,-exported_symbols_list,coders/.libs/tiff-symbols.expsym
libtool: link: ( cd "coders/.libs" && rm -f "ept.la" && ln -s "../ept.la" "ept.la" )
libtool: link: ( cd "filters/.libs" && rm -f "analyze.la" && ln -s "../analyze.la" "analyze.la" )
libtool: link: ( cd "coders/.libs" && rm -f "jpeg.la" && ln -s "../jpeg.la" "jpeg.la" )
libtool: link: ( cd "coders/.libs" && rm -f "jp2.la" && ln -s "../jp2.la" "jp2.la" )
libtool: link: ( cd "coders/.libs" && rm -f "webp.la" && ln -s "../webp.la" "webp.la" )
libtool: link: ( cd "coders/.libs" && rm -f "tiff.la" && ln -s "../tiff.la" "tiff.la" )
make: *** [install] Error 2

**Comment by davea** [comment]
Thanks for letting me know. I've just committed an update with the latest upstream changes, hopefully that works for you.
